AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AccountIDs:
    Description: "IDs of accounts permitted to register"
    Type: CommaDelimitedList
    Default: "644160558196"
Resources:
  RegistrationHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-register"
      Handler: "main"
      Tags:
        App: OmniSSM
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Environment:
        Variables:
          OMNISSM_REGISTRATIONS_TABLE: !Ref RegistrationsTable
          OMNISSM_ACCOUNT_WHITELIST: !Join [ ",", !Ref AccountIDs ]
      Events:
        RegisterInstance:
          Properties:
            Method: POST
            Path: /register
          Type: Api
        RegisterId:
          Properties:
            Method: PATCH
            Path: /register
          Type: Api
  RegistrationsTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: omnissm-registrations
      Tags:
        App: OmniSSM
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      
